### ISSUE TITLE
Xindy requires libcurses.o.5

### ISSUE THREAD

**Issue by wujastyk** [debian-tex/xindy#2]
```
$ xindy --version
xindy release: 2.5.1
xindy script version: 1.18
xindy kernel version: 3.0
CLISP version 2.49.92 (2018-02-18) (built on bulldog [127.0.0.1])
architecture: X86_64
```

In the release with TeXLive 2020, updated today 2020-07-09, xindy requires libcurses.o.5 . This is no longer standard in Linux Mint 20 (or probably in Ubuntu 20), which installs libcurses6. So xindy won't run until you have installed libncurses5 from the repository.

**Comment by norbusan** [comment]
Hi Dominik,

thanks for the report, but your are talking about TUG TeX Live, right, not Debian TeX Live? This here is the package for Debian, which is rebuilt on Debian with the proper versions.

The version in TeX Live depends on ncurses, what a curse. I need to try to rebuild it with static linking. But you might better report these kind of things to tlbuild@tug.org since this repository is only the packaging for Debian.

All the best

Norbert

**Comment by wujastyk** [comment]
Ah, I see Norbert.  Thanks.   Yes, I was talking about TUG TeX Live.

I was looking around for the right place, and the Debian one was the only
repo I could find with xindy version 2.5.1 (as in TeXlive).  There seems to
be a bit of a mess regarding xindy, with old, unmaintained versions and
not-updated websites.  It's hard to know what the "true home" of the xindy
source code is, at present.

--

How are you, and where are you?

All the best from Canada,
Dominik

--
Professor Dominik Wujastyk
<https://apps.ualberta.ca/directory/person/wujastyk>
,

Singhmar Chair in Classical Indian Society and Polity
,

Department of History and Classics <http://historyandclassics.ualberta.ca/>
,
University of Alberta, Canada
.


South Asia at the U of A:

sas.ualberta.ca
